In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

In [4]:
df=pd.read_csv("data/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df=df.drop(columns=["PassengerId","Cabin","Ticket"], axis=1)
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,S

In [6]:
df["family_size"]=df["SibSp"]+df["Parch"]+1
df=df.drop(columns=["SibSp","Parch"], axis=1)
df.head()

,Survived,Pclass,Name,Sex,Age,Fare,Embarked,family_size
0,0,3,"Braund, Mr. Owen Harris",male,22.0,7.2500,S,2
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,C,2
2,1,3,"Heikkinen, Miss. Laina",female,26.0,7.9250,S,1
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,S,2
4,0,3,"Allen, Mr. William Henry",male,35.0,8.0500,S,1

In [7]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Survived     891 non-null    int64
 1   Pclass       891 non-null    int64
 2   Name         891 non-null    object
 3   Sex          891 non-null    object
 4   Age          714 non-null    float64
 5   Fare         891 non-null    float64
 6   Embarked     889 non-null    object
 7   family_size  891 non-null    int64
dtypes: float64(2), int64(3), object(3)
memory usage: 55.8+ KB

In [9]:
df.isna().sum()

Survived         0
Pclass           0
Name             0
Sex              0
Age            177
Fare             0
Embarked         2
family_size      0
dtype: int64

In [10]:

df["Title"]=df["Name"].str.extract("([A-Za-z]+)\.")
df.sample(10)

<>:1: SyntaxWarning: invalid escape sequence '\.'
<>:1: SyntaxWarning: invalid escape sequence '\.'
C:\Users\ANIKET GUPTA\AppData\Local\Temp\ipykernel_8936\3647052917.py:1: SyntaxWarning: invalid escape sequence '\.'
  df["Title"]=df["Name"].str.extract("([A-Za-z]+)\.")

,Survived,Pclass,Name,Sex,Age,Fare,Embarked,family_size,Title
504,1,1,"Maioni, Miss. Roberta",female,16.0,86.5000,S,1,Miss
295,0,1,"Lewy, Mr. Ervin G",male,NaN,27.7208,C,1,Mr
730,1,1,"Allen, Miss. Elisabeth Walton",female,29.0,211.3375,S,1,Miss
397,0,2,"McKane, Mr. Peter David",male,46.0,26.0000,S,1,Mr
440,1,2,"Hart, Mrs. Benjamin (Esther Ada Bloomfield)",female,45.0,26.2500,S,3,Mrs
179,0,3,"Leonard, Mr. Lionel",male,36.0,0.0000,S,1,Mr
378,0,3,"Betros, Mr. Tannous",male,20.0,4.0125,C,1,Mr
485,0,3,"Lefebre, Miss. Jeannie",female,NaN,25.4667,S,5,Miss
140,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,15.2458,C,3,Mrs
853,1,1,"Lines, Miss. Mary Conover",female,16.0,39.4000,S,2,Miss

In [11]:
# df["AgeGroup"]=pd.cut(df["Age"], bins=[0, 18, 50, np.inf], labels=["Child", "Adult", "Senior"])

In [12]:
df["Embarked"]=df["Embarked"].fillna(df["Embarked"].mode()[0])
df.head()

,Survived,Pclass,Name,Sex,Age,Fare,Embarked,family_size,Title
0,0,3,"Braund, Mr. Owen Harris",male,22.0,7.2500,S,2,Mr
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,C,2,Mrs
2,1,3,"Heikkinen, Miss. Laina",female,26.0,7.9250,S,1,Miss
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,S,2,Mrs
4,0,3,"Allen, Mr. William Henry",male,35.0,8.0500,S,1,Mr

In [13]:
df["Title"].value_counts()

Title
Mr          517
Miss        182
Mrs         125
Master       40
Dr            7
Rev           6
Col           2
Mlle          2
Major         2
Ms            1
Mme           1
Don           1
Lady          1
Sir           1
Capt          1
Countess      1
Jonkheer      1
Name: count, dtype: int64

In [14]:
count =df["Title"].value_counts()
df["Title"]=df["Title"].replace(count[count<10].index,"Rare")
df.to_csv("data/Titanic-Dataset-Processed.csv", index=False)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=["Survived","Name"]), df["Survived"], test_size=0.3, random_state=42)

In [16]:
X_train.head()

     Pclass     Sex   Age     Fare Embarked  family_size   Title
445       1    male   4.0  81.8583        S            3  Master
650       3    male   NaN   7.8958        S            1      Mr
172       3  female   1.0  11.1333        S            3    Miss
450       2    male  36.0  27.7500        S            4      Mr
314       2    male  43.0  26.2500        S            3      Mr

In [17]:
tranformer=ColumnTransformer(transformers=[
    ("tnf1",SimpleImputer(),["Age"]),
    ("tnf2",OneHotEncoder(drop="first",sparse_output=False),["Title","Sex"]),
    ("tnf3",OrdinalEncoder(categories=[[1,2,3],["S","C","Q"]]),["Pclass","Embarked"])
],remainder="passthrough")
X_train_new= tranformer.fit_transform(X_train)
X_test_new= tranformer.transform(X_test)

In [18]:
print(X_train_new.shape)
print(X_test_new.shape)

(623, 10)
(268, 10)

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
model=LogisticRegression()
model.fit(X_train_new,y_train)
y_pred=model.predict(X_test_new)
accuracy_score(y_test,y_pred)

c:\Users\ANIKET GUPTA\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.8059701492537313